stages:
- check
- deploy

檢查程式碼:
  stage: check
  environment:
    name: check
  variables:
    STUFF_DEBUG: 1
  script:
  - stuff source

打包展示版:
  stage: deploy
  environment:
    name: demo/$CI_COMMIT_REF_NAME
  variables:
    STUFF_DEBUG: 0
    STUFF_MODE: demo
    STUFF_UPLOAD: review
  script:
  - stuff deploy
  when: manual
  only:
  - tags

打包除錯版:
  stage: deploy
  environment:
    name: test/$CI_COMMIT_REF_NAME
  variables:
    STUFF_DEBUG: 0
    STUFF_MODE: test
    STUFF_UPLOAD: review
  script:
  - stuff deploy
  when: manual
  only:
  - tags

打包正式版:
  stage: deploy
  environment:
    name: release/$CI_COMMIT_REF_NAME
  variables:
    STUFF_DEBUG: 0
    STUFF_MODE: release
    STUFF_UPLOAD: review
  script:
  - stuff deploy
  only:
  - tags

測試機:
  stage: deploy
  environment:
    name: beta/$CI_COMMIT_REF_NAME
  variables:
    STUFF_DEBUG: 0
    STUFF_MODE: release
    STUFF_UPLOAD: beta
  script:
  - stuff deploy
  only:
  - beta

測試機(log):
  stage: deploy
  environment:
    name: alpha/$CI_COMMIT_REF_NAME
  variables:
    STUFF_DEBUG: 0
    STUFF_MODE: test
    STUFF_UPLOAD: beta
  when: manual
  script:
  - stuff deploy
  only:
  - beta

測試機(demo):
  stage: deploy
  environment:
    name: beta/$CI_COMMIT_REF_NAME
  variables:
    STUFF_DEBUG: 0
    STUFF_MODE: demo
    STUFF_UPLOAD: beta
  when: manual
  script:
  - stuff deploy
  only:
  - beta

alpha機:
  stage: deploy
  variables:
    STUFF_DEBUG: 1
    STUFF_MODE: test
    STUFF_UPLOAD: alpha_name
  script:
  - stuff deploy
  environment:
    name: alpha/$CI_COMMIT_REF_NAME
  only:
  - alpha
