stages:
- check
- build
- deploy

最佳化程式碼:
  stage: build
  environment:
    name: build
  variables:
    STUFF_DEBUG: 1
  script:
  - stuff build
  only:
  - tags

檢查程式碼:
  stage: check
  environment:
    name: check
  variables:
    STUFF_DEBUG: 1
  script:
  - stuff source

打包展示版:
  stage: deploy
  environment:
    name: demo/$CI_COMMIT_REF_NAME
  variables:
    STUFF_DEBUG: 0
    STUFF_MODE: demo
    STUFF_UPLOAD: review
  script:
  - stuff deploy
  when: manual
  only:
  - tags

打包有log版:
  stage: deploy
  environment:
    name: test/$CI_COMMIT_REF_NAME
  variables:
    STUFF_DEBUG: 0
    STUFF_MODE: test
    STUFF_UPLOAD: review
  script:
  - stuff deploy
  when: manual
  only:
  - tags

打包無log版:
  stage: deploy
  environment:
    name: release/$CI_COMMIT_REF_NAME
  variables:
    STUFF_DEBUG: 0
    STUFF_MODE: release
    STUFF_UPLOAD: review
  script:
  - stuff deploy
  only:
  - tags
