---
name: sample
title: 
group: demo
company: com
description: webapp demo sample
version: 1.9.8
generatorVendor: v2
framework:
  name: stuff
  version: 5.0.0
  builder: rollup
  skipCommandTerser: true
  useCodeSplitting: true
# template:
#   format: game
#   standalone: true
#   debug:
#     appInLibMap: true
#     format: iife
#     src: template/debug.html
#     dest: index.html
#   release:
#     appInLibMap: true
#     format: iife
#     src: template/release.html
#     dest: index.html
author:
  name: astro
  email: www@astrocorp.com.tw
  url: www.astrocorp.com.tw
licenses:
  -
    type: MIT
    url: undefined/blob/master/LICENSE-MIT
keywords:
  - HTML5
  - game
  - es6
  - app
#excluded:
#  autoTest: true

