demo:
  six: #六人桌
    config:
      limit: #有限注
        scrollVisible: false
      free:  #無限注
        scrollVisible: true
      record: #播放遊戲紀錄
        showRecord: true  
      hide : false #顯示模式
    position:
      community: #公牌
        coin: #小計金額位置
        - {x: 980,y: 639}
        - {x: 832,y: 565}
        - {x: 1128,y: 565}
        - {x: 758,y: 663}
        - {x: 1212,y: 663}
        poker: #撲克牌位置
        - {x: 725,y: 463}
        - {x: 820,y: 463}
        - {x: 915,y: 463}
        - {x: 1010,y: 463}
        - {x: 1105,y: 463}
      counter: #籌碼
      - {x: 843, y: 728}
      - {x: 531, y: 687}
      - {x: 529, y: 353}
      - {x: 936, y: 343}
      - {x: 1406, y: 353}
      - {x: 1406, y: 687}
      player: #玩家
      - {x: 742, y: 819, type: center}
      - {x: 20, y: 560, type: right}
      - {x: 20, y: 211, type: right}
      - {x: 742, y: 95, type: right}
      - {x: 1465, y: 211, type: left}
      - {x: 1465, y: 560, type: left}
