name: 更新
on:
  push:
    tags:
      - v*
jobs:
  release:
    env:
      STUFF_DEBUG: 1
      STUFF_MODE: release
      STUFF_UPLOAD: beta
    runs-on: [self-hosted, x64, game]
    name: 營運機組
    steps:
      - uses: actions/checkout@v3
      - name: 說明 一
        run: pwd
      - name: 說明 二 
        run: export
