name: 更新
on:
  push:
    tags:
      - v*
jobs:
  release:
    env:
      STUFF_DEBUG: 1
      STUFF_MODE: release
      STUFF_UPLOAD: review
    runs-on: [self-hosted, x64, game]
    name: 營運版
    steps:
      - uses: actions/checkout@v3
      - name: 部署
        run: stuff deploy
      - name: 測試用
        run: export

